target_sample_rate: 100.0
subject_code: DemoSubject
project_name: test
precision: float
pre_downsample: 4.0
kernel_table:
  Frequency:
  - 2
  - 12
  - 22
  - 32
  - 42
  - 52
  - 62
  - 72
  - 82
  - 92
  - 102
  - 112
  - 122
  - 132
  - 142
  - 152
  - 162
  - 172
  - 182
  - 192
  Cycles:
  - 3.0
  - 6.0
  - 8.0
  - 9.0
  - 11.0
  - 11.0
  - 12.0
  - 13.0
  - 14.0
  - 15.0
  - 15.0
  - 16.0
  - 16.0
  - 17.0
  - 17.0
  - 18.0
  - 18.0
  - 19.0
  - 19.0
  - 20.0
